### PR TITLE
More osgearth features

### PR DESCRIPTION
**Pull request by tqjxlm**
1. Compatible with osgEarth 2.10
2. Support geocentric map with EarthManipulator (not usable yet)
3. Fix display issues: higher FPS, dynamic nearFarRatio, nodeMask mechanism
4. Fix plugin: AddModel, ModelFlatten, OrthoMap
5. Remove plugin: PathRoaming

### CODE REVIEW

**Comment by tqjxlm** [comment]
[Compatibility with osgEarth 2.10](https://trello.com/c/rYoUze7h/46-compatibility-with-osgearth-210)

**Comment by tqjxlm** [comment]
[Geodetic map support](https://trello.com/c/Y7vBh7AS/9-geodetic-map-support)

**Comment by mola** [comment]
If can use this code style:
https://github.com/mola/codestyle

use uncrustify

**Comment by tqjxlm** [comment]
> If can use this code style:
> https://github.com/mola/codestyle
> 
> use uncrustify

Thanks for the reminding. I'll do it in future commits.

By the way, I tried uncrusity over the whole repository using the style cfg, except for generated files. It seems not all the source files have been formatted. Is it because the uncrustify version differs?

If not the case, maybe a full formating should be done in a later PR (not this one, it is over-complex now). The code style might also need slight modification to keep compliance with the Qt and/or OSG convention.

**Comment by tqjxlm** [comment]
Feature changes in this branch should be stale now. The demos uploaded in #4 have used features from this branch.

**Review by chen-san — APPROVED** [review]

**Pull request merged**
